Add recommendations
vasilenkodm/java-filmorate pull request #11
Opened 2023-03-31 16:01 UTC by ArtakJava

Реализация рекомендаций по фильмам для пользователей

https://www.notion.so/5cc6938fa7704059a73bcc8a8e9fd1d1?v=d7fe946823974627817e103beef91118&p=41788353c2e1411a87c142e6e3068a12&pm=s

2023-03-31 16:58 UTC, vasilenkodm requested changes
Ты чемпион с минимумом замечаний! ;)
Главное, что у тебя получился сложный запрос и Постман его принял.
Подправь момент, который я указал иначе ревьювер не пропустит.

2023-03-31 16:58 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmInMemoryStorage.java
> +        return null;
Сделай тут выброс  throw new FeatureNotSupportedException(this.getClass(), log);
Результат запроса не должен быть null

2023-03-31 18:22 UTC, panovaaolga approved these changes
Согласна с Димой) Единственное замечание, которое я могла бы добавить, ты уже исправил, спасибо! Работу запроса я проверила, все отработало корректно.

2023-04-02 06:30 UTC, vasilenkodm approved these changes

2023-04-02 07:32 UTC, merged