Add search
vasilenkodm/java-filmorate pull request #12
Opened 2023-04-01 05:52 UTC by panovaaolga

https://www.notion.so/2bf8389ba43f410b9c4b6322a651d6a2?pvs=4

Описание задачи

2023-04-01 07:32 UTC, vasilenkodm requested changes
В целом все хорошо, но запрос надо переработать, это основное замечание.

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getSearchedFilms(@RequestParam(name = "query") String query,
Надо как-то обыграть и проконтролировать ситуацию, когда параметра query нет в запросе, дать значение по умолчанию какое-то, например "", или проверить на null. Ну и для таких вариантов выбрасывать MethodArgumentNotValidException. Т.е показать, что запрос сделан неверно и вот по какой причине. Думаю Ревьювер обратит на это внимание
{
    "timestamp": "2023-04-01T06:53:06.775+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/films/search"
}

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +        if (by.contains("title")) {
Меня смущает такой способ собирания списка полей, это не очень безопасный и гибкий подход. Предлагаю сделать статисескую Мапу, с ключами которые приходят из запроса ("title", "director") и соответствующими им значениями полей. "title", "director" тоже сделать константами (static final). В цикле по Сету перебрать значения и выдернуть нужное из Мапы. но цикл не через for(int i=...), а через for (String s: by) ...

Всмотрелся в код ниже и думаю, что все это надо сделать иначе. просто через 
if (by.contains("director")) ...

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                "LEFT JOIN FilmDirector AS fd ON fd.film_id = f.film_id " +
У фильма может быть несколько режиссеров и тут надо как-то иначе обыграть условие, возможно сделать подзапрос

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +            for (int i = 0; i < by.size(); i++) {
Для итерируемых интерфейсов лучше писать цикл через "for (String s: by) ."

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                        " ILIKE '%" + query + "%' OR ");
Думаю лучшим вариантом будет использование SqlParameterSource (см. метод public Film read(final FilmIdType id)), там должно быть экранирование специальных символов " ' ", ";" и пр.. Склеивание маски для поиска (%...%)не потребуется, если сделаешь через SqlParameterSource. Если ревьювер заметит, то не пропустит это.

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +    private boolean areValidNames(Set<String> by) {
Думаю это можно им нужно будет убрать, если переделаешь предшествуюший метод

2023-04-01 07:32 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmInMemoryStorage.java
> +        throw new FeatureNotSupportedException("Функция не поддерживается", this.getClass(), log);
Можешь заменить на вызов с другим набором аргументов, там уже есть текст:
FeatureNotSupportedException(this.getClass(), log);

2023-04-02 06:29 UTC, vasilenkodm approved these changes

2023-04-02 07:47 UTC, ArtakJava approved these changes

2023-04-03 08:53 UTC, merged