Спринт-12
vasilenkodm/java-filmorate pull request #17
Opened 2023-04-03 20:56 UTC by vasilenkodm

Групповой проект 12-го спринта.

2023-04-04 09:13 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-04-04 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    time_stamp BIGINT not null,
Для времени я бы советовал использовать временнЫе типы данных:
https://habr.com/ru/post/61391/

2023-04-04 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    user_id BIGINT not null references UserInfo (user_id) on delete cascade,
Почему где-то `references` рядом с полем, а где-то отдельным выражением? 
Это ваглядит немного странно

2023-04-04 09:13 UTC, LexLippi commented on src/main/resources/schema.sql
> +    entity_id BIGINT not null
Зачем создание таблиц дублируется?

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToReviewIdTypeConverter.java
> +@SuppressWarnings("unused")
Если этот класс не используется, может его стоит удалить?

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToDirectorIdTypeConverter.java
> +@SuppressWarnings("unused")
Аналогичный вопрос

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +                                     @RequestParam(defaultValue = "10", required = false) Integer count) {
Если есть `defaultValue`, то нет необходимости в `required = false`

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDAO.java
> +        String sqlStatement = String.format("select count(*) from Director where %1$s = :%1$s", ID_FIELD);
Для этого имеет смысл использовать оператор `exists`:
https://www.w3schools.com/sql/sql_exists.asp

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDAO.java
> +    public void addEvent(Long userId, Long entityId, EventType eventType, OperationType operationType) {
Идентификатор созданного события нас не интересует?

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                GenreDAO.ID_FIELD, FILMGENRE_GENRE_ID, FILMGENRE_FILM_ID);
Этот запрос необходимо переписать с помощью `join`

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                DirectorDAO.ID_FIELD, FILMDIRECTOR_DIRECTOR_ID, FILMDIRECTOR_FILM_ID);
И этот тоже

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                break;
Большая часть запроса совпадает, может не заниматься копипастой, а в `switch-case` разрулить толко те параметры, которые нас действительно интересуют?

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                                  "and film_id not in (select film_id " +
Нельзя использовать такое количество подзапросов. Необходимо переписать это с помощью `join`

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
Общее требование к этому и всем другим классам - нельзя пользоваться вложенными подзапросами. Наставник может вам помочь, если есть вопросы, как этого избежать.

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +
У вас же есть аннотация `getter`, зачем это еще?

2023-04-04 09:13 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/RecommendationsService.java
> +    //GET /users/{userId}/recommendations — список рекомендаций по фильмам.
Сервис не знает ничего про `REST`-эндпоинты, он просто предоставляет некоторый `API` вне зависимости от того, кто его вызывает

2023-04-04 12:41 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToReviewIdTypeConverter.java
> +@SuppressWarnings("unused")
Это конвертор строки в объект, они все используются
![изображение](https://user-images.githubusercontent.com/59884542/229794689-8702e214-a205-4b9f-aaaa-24d819aa8e20.png)

2023-04-04 12:42 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToDirectorIdTypeConverter.java
> +@SuppressWarnings("unused")
Аналогично. Это конвертор строки в объект, они все используются
![изображение](https://user-images.githubusercontent.com/59884542/229794723-253b49d9-544b-46ad-a746-e42b5686d9b1.png)

2023-04-04 12:45 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
> +                break;
Категорически не согласен. Это два похожих, но все такие разных запроса, для двух разных случаев. Хоть и по одной таблице, но с разным порядком и условиями.
Можно завешаться условиями, но здесь нет вариативности в тексте запроса, мы просто читабельно и многострочно написали две строки.

2023-04-04 16:00 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/EventDAO.java
> +    public void addEvent(Long userId, Long entityId, EventType eventType, OperationType operationType) {
Возврат кода события добавили, но нас оно действительно не интересовало.

2023-04-04 18:16 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDAO.java
> +        String sqlStatement = String.format("select count(*) from Director where %1$s = :%1$s", ID_FIELD);
Тут скорее имеет смысл использовать "select top 1 ..." , а не exists, но так как мне надо просто проверить наличие записей для заданного ИД, то "select count(*) " было гораздо удобнее, целесообразнее и не несет оверхед .  При использовании "select top 1 ..." мне надо формировать список, оценивать его размер и пр., это те же накладные расходы, без профита  и с нагромождением подобного  - https://javabydeveloper.com/fix-emptyresultdataaccessexception-incorrect-result-size-expected-1-actual-0/
В where уже стоит условие по первичному ключу, поиск выполнится по индексу.

2023-04-05 20:37 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDAO.java
постарались везде убрать "in", осталось только в поиске. но там нет"коррелирующих подзапросов", там определение множества значений режиссеров.

2023-04-06 09:10 UTC, LexLippi approved these changes
Привет!

Отличная работа!
Поздравляю всех участников группового проекта.

Оставил два замечания, которые сделали бы проект еще лучше!

Желаю всем удачи в следующих спринтах!

2023-04-06 09:10 UTC, LexLippi commented on src/main/resources/schema.sql
> +create TABLE IF NOT EXISTS UserInfo (
Кстати, это не надо исправлять, но просто на будущее.
Очень странно читать код, где какие-то ключевые слова в нижнем регистре, а какие-то наоборот. Надо как-то стратегию выработать. Либо все в нижнем, либо все в верхнем.

2023-04-06 09:10 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDAO.java
> +        final String sqlStatement = String.format("select top :%2$s * from Review where %1$s = :%1$s ", FILM_ID_FIELD, COUNT_FIELD);
Лучше не использовать по возможности такой запрос. Так как он не задекларирован в стандарте `SQL` и его реализуют только некоторые СУБД, если нам потребуется переехать (что в теории возможно) на другую СУБД, то нам придется переписывать эти запросы чего бы не хотелось. В идеале, надо использовать оператор `FETCH`. К тому же надо отсортировать записи по какой-то колонке. Иначе запрос может возвращать разные результаты в разные временные промежутки с одними и теми же параметрами.

https://www.w3schools.com/sql/sql_top.asp

2023-04-06 09:39 UTC, DariaChagadaeva approved these changes

2023-04-06 09:46 UTC, merged