Add database
vasilenkodm/java-filmorate pull request #4
Opened 2023-03-02 14:59 UTC by vasilenkodm

Структура БД обсуждалась в Пачке, выложена на Гитхабе в файле https://github.com/vasilenkodm/java-filmorate/blob/main/DatabaseSchema.md.
В процессе работы в схеме БД подкорректированы названия таблиц и полей.

2023-03-03 08:20 UTC, LexLippi requested changes
Привет, отличная работа!

Интересный подход к абстрагированию операций.
Единственное, что хотел отметить, надо понимать, что в жизни, и в рабочих проект такой подход не всегда применим, так как часто даже к таким базовым операциям, как `CRUD` появляются дополнительные условия, делающими такое обобщение излишним.

В плане того, что код, который можно было написать в несколько тысяч строк, превращается в десятки и сотни тысяч строк кода, из-за необходимости поддерживать всю это конструкцию с абстрагированиям (кэши, проверки, оптимизации на уровне SQL), поэтому всегда надо подумать, а не придется ли нам потом с болью поддерживать этого монстра, чем просто повторить код для похожих вроде бы `CRUD` операций.

Поэтому, исходя из моего опыта, сначала всегда пишут некоторое `MVP` приложения с повторениями, а потом занимаются такого рода абстрагированием.

Но работа замечательная!

Есть пару замечаний и советов, которое хотелось бы чтобы ты исправил.

Желаю удачи!!!

2023-03-03 08:20 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private final RankMPAStorage mpaStorage;
В тестах эти модификаторы доступа ни к чему

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:file:./db/filmorate
Комментарии с предыдущими или некорректными значениями лучше не оставлять

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/data.sql
> +--
Зачем здесь пустой комментарий?)

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/data.sql
> +insert into RankMPA (rankMPA_name) values ('G'), ('PG'), ('PG-13'), ('R'), ('NC-17');
А если данные в таблице уже есть? Мы же, наверное, не хотим повторно добавлять имеющиеся данные.
Можно подумать, как в таком случае использовать оператор `MERGE`.

https://en.wikipedia.org/wiki/Merge_(SQL)

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/schema.sql
> +CREATE TABLE Film (
Значения по умолчанию в этой таблице мне кажутся странными.
 
 
 Пустое название и пустое описание, а также продолжительность фильма 1 минута. 
 Мы таким образом гарантируем для данных в базе не больше, чем если бы там лежали `NULL`.
 
 Может быть есть возможность обойтись без значений по умолчанию?

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/schema.sql
> +  description VARCHAR(200) NOT NULL DEFAULT '',
`varchar(200)`, кажется, маловато для описания фильма.
если мы заранее не знаем размер текста, то лучше использовать тип данных `text`

2023-03-03 08:20 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
Эта таблица не совпадает с той, что представлена на схеме.

Надо поправить либо схему, либо таблицу

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/SomeType.java
> +        @SuppressWarnings("unchecked")
Лучше не использовать `unchecked cast` по возможности, так как это является Code Smell (запахом кода), что с твоим кодом что-то не так.

Вот здесь можно посмотреть, как избавиться от этого
https://www.baeldung.com/java-unchecked-conversion#2-checking-type-conversion-before-using-the-raw-type-collection

Там приводится пример с коллекцией, но кажется, что он легко переделывается на твой случай

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/SomeType.java
> +public abstract class SomeType<T extends Comparable<T>> implements java.io.Serializable, Comparable<SomeType<T>> {
Мне кажется более подходящим было бы название `ValueObject`, 
Поскольку это действительно класс, который хранит одно значение.

https://en.wikipedia.org/wiki/Value_object

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    void addFriend(UserIdType userId, UserIdType _friendId);
Использование нижнего подчеркивания в названиях переменных - не особенно отвечает Java Naming Convention.

Люди обычно пытаются это привнести из других языков, где это необходимо, но в Java я не вижу смысла в использовании таких переменных

https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/rankmpa/RankMPAInMemoryStorage.java
> +public class RankMPAInMemoryStorage extends BaseItemInMemoryStorage<RankMPAIdType, RankMPA> implements RankMPAStorage {
Все `InMemoryStorage` советуем удалить в данном спринте, так как дальнейшее их поддерживание будет отдельной головной болью

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/BaseItemInMemoryStorage.java
> +//public interface BaseItemStorage<K extends SomeType<?>, T extends BaseItem> {
Такие комментарии стоит удалять

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/BaseItemInMemoryStorage.java
> +    protected final Map<K, T> items = new TreeMap<>();
В жизни вместо `TreeMap` стараемся использовать `HashMap`, так как по умолчанию в `HashMap` встроена довольно хорошая хэш-функция, которая на большинстве примеров дает  преимущество по скорости доступа к данным

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/BaseItem.java
> +abstract class BaseItem<K, T extends BaseItem<K, T>> {
Стоит добавить явный модификатор доступа

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/BaseItem.java
> +    BaseItem() {
1. Аналогично можно добавить модификатор доступа
2. Либо использовать встроенную в `lombok` аннотацию - `NoArgsConstructor`

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/BaseItemController.java
> +    public T readItem(@PathVariable final K _id) {
Кстати, немного странно, что где-то ты используешь в названии `get` - `getAllItems`, а где-то `read` - `readItem`. Лучше остановиться на каком-то одном глаголе

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void addLike(@PathVariable(name="filmId") FilmIdType _filmId, @PathVariable(name="userId") UserIdType _userId) {
кажется, проще было бы использовать одинаковые названия в пути и для переменных

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToGenreIdTypeConverter.java
> +public class StringToGenreIdTypeConverter implements Converter<String, GenreIdType> {
Я бы посоветовал использовать здесь шаблон `enum-singleton`

https://www.geeksforgeeks.org/advantages-and-disadvantages-of-using-enum-as-singleton-in-java/

2023-03-03 08:20 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	}
Это очень странный метод, к чему он здесь?

2023-03-03 08:20 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +		final String NAME1 = "+++++";
1. Это не константы класса, так что стоит использовать конвенцию наименования локальных переменных.
2. Это не обязательно, но советую не использовать цифровые идентификаторы в названиях переменных, с ними сложнее работать. Их вполне можно заменить на аналоги `firstName`, `secondName`

2023-03-03 08:20 UTC, LexLippi commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Непонятно, почему логически разные тесты, относящиеся к разным контроллерам и сущностям находятся в одном классе - это не лучший вариант

2023-03-03 08:20 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        //storage.addFriend(_friendId, _userId);
не стоит оставлять такие строки

2023-03-03 11:25 UTC, vasilenkodm commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	private final RankMPAStorage mpaStorage;
Если убрать эти модификаторы, то перестает становится бесполезной аннотация @RequiredArgsConstructor(onConstructor_ = @Autowired) и я получаю NPE. Это сделано на основе примера из ТЗ.
https://practicum.yandex.ru/learn/java-developer/courses/25d33887-e804-43d5-a330-b5539e8dcd6c/sprints/102476/topics/fde7e767-12d4-497f-a938-624d06574af1/lessons/c2cb4c80-655d-4646-acd8-89a4bebe879b/
![изображение](https://user-images.githubusercontent.com/59884542/222708457-b7b28206-9d6b-4fdc-88c7-a236e9f5c995.png)

2023-03-03 15:07 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToGenreIdTypeConverter.java
> +public class StringToGenreIdTypeConverter implements Converter<String, GenreIdType> {
Данный шаблон я не смогу использовать т.к. я не могу переопределить методы требующиеся для сравнения объектов - compareTo, hashCode и  equals. Они помечены как final в java.lang.Enum. Кроме того, я был бы вынужден повторять весь код в каждом новом классе т.к. у Enum есть нюансы с наследованием.

2023-03-04 00:46 UTC, vasilenkodm commented on src/main/resources/schema.sql
> +  description VARCHAR(200) NOT NULL DEFAULT '',
У нас было требование валидации описания "до 200 символов" в предшествующем ТЗ, это требование не отменяли.

2023-03-04 00:55 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/type/StringToGenreIdTypeConverter.java
> +public class StringToGenreIdTypeConverter implements Converter<String, GenreIdType> {
Снова провел опыты. У меня тут не может быть такой Синглтон, т.к. мне нужны разные значения, а не одно из элемента перечисления. Кроме того  элементы Энума не могут создаваться
![изображение](https://user-images.githubusercontent.com/59884542/222863609-c52911c6-8c30-4a18-b50d-e0522e5f8f59.png)

2023-03-04 02:14 UTC, vasilenkodm commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    void addFriend(UserIdType userId, UserIdType _friendId);
"_" использую только для выделения аргумента метода, для меня это повышает читаемость кода. Это из опыта программирования на другом языке (не Питона), но это было не требование, а рекомендация по стилю.

2023-03-04 07:21 UTC, LexLippi reviewed
Привет!

Отличные доработки, есть пара замечаний, но они не обязательные, желательно, конечно, их исправить хотя бы к следующему спринту, но если сейчас не хочется, то можешь перезаслать работу в таком виде, я приму.

Желаю удачи!

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/BaseItemDbStorage.java
> +        return dao.read(id);
В идеале, не делать два запроса к СУБД, любой запрос это довольно тяэелая операция, и когда есть возможность обходиться без него, то лучше обходиться без него.

Правильный результирующий объект вполне можно построить из вставляемого `_item` и идентификатора, который нам вернули по результатам вставки.

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/BaseItemDbStorage.java
> +        return dao.read(_item.getId());
Аналогично, замечанию выше, лучше не обращаться к СУБД лишний раз

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/FilmIdType.java
> +public class FilmIdType extends ValueType<Long> {
Не помешает модификатор `final`

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/GenreIdType.java
> +public class GenreIdType extends ValueType<Integer> {
Не помешает идентификатор `final`

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/RankMPAIdType.java
> +public class RankMPAIdType extends ValueType<Integer> {
`final`, в классах, от которых мы не захотим иметь наследников, всегда лучше прописывать этот модификатор

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/UserIdType.java
> +public class UserIdType extends ValueType<Long> {
`final`

2023-03-04 07:21 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/type/ValueType.java
> +        return this.value.equals(other.value);
У нас нет уверенности, что `this.value` это не `null`, в таком случае лучше использовать `Objects.equals` для сравнения объектов

2023-03-04 17:07 UTC, vasilenkodm commented
Допилил по рекомендациям. При вставке новых объектов в БД, чтобы развязать объекты, сделал "клонирование" через сериализацию. Стандартное клонирование не развяжет все поля в "результате" от "источника"

2023-03-05 08:53 UTC, LexLippi approved these changes
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!!!

2023-03-05 09:06 UTC, merged